controller_list:
  - name: fake_left_controller
    type: $(arg execution_type)
    joints:
      - L_SFE
      - L_SAA
      - L_HR
      - L_EB
      - L_WR
      - L_WFE
      - L_WAA
  - name: fake_right_controller
    type: $(arg execution_type)
    joints:
      - R_SFE
      - R_SAA
      - R_HR
      - R_EB
      - R_WR
      - R_WFE
      - R_WAA
initial:  # Define initial robot poses.
#  - group: left
#    pose: home

  []